/*
 * generated by Xtext
 */
package com.rockwellcollins.atc.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import com.rockwellcollins.atc.ui.internal.LimpActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LimpExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return LimpActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return LimpActivator.getInstance().getInjector(LimpActivator.COM_ROCKWELLCOLLINS_ATC_LIMP);
	}
	
}
