/*
 * generated by Xtext
 */
package com.rockwellcollins.atc;


/**
 * Initialization support for running Xtext languages without equinox extension
 * registry
 */
public class LimpStandaloneSetup extends LimpStandaloneSetupGenerated {
	public static void doSetup() {
		LimpInjectorUtil.doStandaloneSetup();
	}
}
