/*
 * generated by Xtext
 */
package com.rockwellcollins.atc.serializer;

import com.google.inject.Inject;
import com.rockwellcollins.atc.services.LimpGrammarAccess;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class LimpSyntacticSequencer extends AbstractSyntacticSequencer {

	protected LimpGrammarAccess grammarAccess;
	protected AbstractElementAlias match_TerminalExpr_LeftParenthesisKeyword_0_0_a;
	protected AbstractElementAlias match_TerminalExpr_LeftParenthesisKeyword_0_0_p;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (LimpGrammarAccess) access;
		match_TerminalExpr_LeftParenthesisKeyword_0_0_a = new TokenAlias(true, true, grammarAccess.getTerminalExprAccess().getLeftParenthesisKeyword_0_0());
		match_TerminalExpr_LeftParenthesisKeyword_0_0_p = new TokenAlias(true, false, grammarAccess.getTerminalExprAccess().getLeftParenthesisKeyword_0_0());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_TerminalExpr_LeftParenthesisKeyword_0_0_a.equals(syntax))
				emit_TerminalExpr_LeftParenthesisKeyword_0_0_a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_TerminalExpr_LeftParenthesisKeyword_0_0_p.equals(syntax))
				emit_TerminalExpr_LeftParenthesisKeyword_0_0_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     '('*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) '*' (rule start)
	 *     (rule start) (ambiguity) '-' expr=UnaryExpr
	 *     (rule start) (ambiguity) 'array' arrayDefinition=[ArrayTypeDef|ID]
	 *     (rule start) (ambiguity) 'choice' '(' first=Expr
	 *     (rule start) (ambiguity) 'init' id=[VariableRef|ID]
	 *     (rule start) (ambiguity) 'not' expr=UnaryExpr
	 *     (rule start) (ambiguity) 'record' recordDefinition=[RecordTypeDef|ID]
	 *     (rule start) (ambiguity) 'second_init' id=[VariableRef|ID]
	 *     (rule start) (ambiguity) boolVal=BOOLEAN
	 *     (rule start) (ambiguity) id=[FunctionRef|ID]
	 *     (rule start) (ambiguity) id=[VariableRef|ID]
	 *     (rule start) (ambiguity) intVal=INT
	 *     (rule start) (ambiguity) realVal=REAL
	 *     (rule start) (ambiguity) stringVal=STRING
	 *     (rule start) (ambiguity) {ArrayAccessExpr.array=}
	 *     (rule start) (ambiguity) {ArrayUpdateExpr.access=}
	 *     (rule start) (ambiguity) {BinaryExpr.left=}
	 *     (rule start) (ambiguity) {IfThenElseExpr.condExpr=}
	 *     (rule start) (ambiguity) {RecordAccessExpr.record=}
	 *     (rule start) (ambiguity) {RecordUpdateExpr.record=}
	 */
	protected void emit_TerminalExpr_LeftParenthesisKeyword_0_0_a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '('+
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) '-' expr=UnaryExpr
	 *     (rule start) (ambiguity) 'choice' '(' first=Expr
	 *     (rule start) (ambiguity) 'not' expr=UnaryExpr
	 *     (rule start) (ambiguity) {ArrayAccessExpr.array=}
	 *     (rule start) (ambiguity) {ArrayUpdateExpr.access=}
	 *     (rule start) (ambiguity) {BinaryExpr.left=}
	 *     (rule start) (ambiguity) {IfThenElseExpr.condExpr=}
	 *     (rule start) (ambiguity) {RecordAccessExpr.record=}
	 *     (rule start) (ambiguity) {RecordUpdateExpr.record=}
	 */
	protected void emit_TerminalExpr_LeftParenthesisKeyword_0_0_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
