/*
 * generated by Xtext
 */
package com.rockwellcollins.atc.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.formatting.IWhitespaceInformationProvider;
import org.eclipse.xtext.ui.editor.syntaxcoloring.AbstractAntlrTokenToAttributeIdMapper;

import com.rockwellcollins.atc.ui.editor.syntaxcoloring.LimpAntlrTokenToAtrributeIdMapper;

/**
 * Use this class to register components to be used within the IDE.
 */
public class LimpUiModule extends com.rockwellcollins.atc.ui.AbstractLimpUiModule {
	public LimpUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	public Class<? extends AbstractAntlrTokenToAttributeIdMapper> bindAbstractAntlrTokenToAttributeIdMapper() {
		return LimpAntlrTokenToAtrributeIdMapper.class;
	}
	
	@Override
	public Class<? extends IWhitespaceInformationProvider> bindIWhitespaceInformationProvider() {
		return IWhitespaceInformationProvider.Default.class;
	}
}
