/*
 * generated by Xtext
 */
package com.rockwellcollins.atc.scoping;



/**
 * This class contains custom scoping description.
 * 
 * Thus far in this project, the default scoping is used.
 * 
 * see : http://www.eclipse.org/Xtext/documentation.html#scoping
 * on how and when to use it 
 *
 */
public class LimpScopeProvider 
	extends org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider {
	

}
