/*
* generated by Xtext
*/
package com.rockwellcollins.atc.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
public class LimpProposalProvider extends com.rockwellcollins.atc.ui.contentassist.AbstractLimpProposalProvider {

}
