/*
 * generated by Xtext
 */
package com.rockwellcollins.atc.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.rockwellcollins.atc.services.LimpGrammarAccess;

public class LimpParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private LimpGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_SL_COMMENT", "RULE_ML_COMMENT");
	}
	
	@Override
	protected com.rockwellcollins.atc.parser.antlr.internal.InternalLimpParser createParser(XtextTokenStream stream) {
		return new com.rockwellcollins.atc.parser.antlr.internal.InternalLimpParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Specification";
	}
	
	public LimpGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(LimpGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
