/*
 * generated by Xtext
 */
package com.rockwellcollins.atc.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class LimpAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("com/rockwellcollins/atc/parser/antlr/internal/InternalLimp.tokens");
	}
}
